Repository TZG-official/Jvav, pull requests merged in 2020-05, with the labels that each got.

#57 卸载Jvav - 新增, 什么是Jvav - 添加新内容
  about/whatis_jvav.html
  download/help/uninstall-jvav.html
Labels: enhancement

#58 为什么选择 Jvav - 文案修改
  about/whatis_jvav.html
Labels: enhancement, help wanted

#74 关于 - 增加关于此梗的注意事项
  about/index.html
Labels: help wanted

#79 什么是 Jvav - 修正错别字
  about/whatis_jvav.html
Labels: bug
